# Production Dockerfile – tiny, secure, fast
FROM node:24-alpine AS builder
WORKDIR /app
COPY ./nivek-vue/package*.json ./
RUN npm install --legacy-peer-deps
COPY ./nivek-vue .
RUN npm run build   # create /app/dist with pure static files

# Final stage – only nginx, no Node, no Vite
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80

# @TODO::should all this be handled in the nginx container directly?